name: 'Pipeline-React-Main'

on:
  push:
    branches:
      - Develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Deploy WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "dev-ducky-as"
          slot-name: "Production"
          package: ./build
