name: 'Pipeline-React-Main'

on:
  push:
    branches:
      - Develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Prepare Deployment Package
        run: |
          mkdir deployment
          cp -r .next/standalone/* deployment/
          cp -r .next/static deployment/.next/static
          cp -r public deployment/public
          cp next.config.mjs deployment/
          cp package.json deployment/

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "WebAppTest-AS"
          slot-name: Production
          package: ./deployment
