name: 'Pipeline-React-Main'
on:
  push:
    branches:
      - Develop
  workflow_dispatch:
permissions:
  contents: read
  # id-token: write  # auskommentiert, damit gar kein OIDC-Flow mehr startet
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: Install dependencies
        run: npm install
      
      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          auth-type: 'service_principal'
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "dev-ducky-as"
          slot-name: "Production"
          package: .
        timeout-minutes: 15
