name: 'Pipeline-React-Main'

on:
  push:
    branches:
      - Develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4BF013AED0674B88EA9E5C66E0DCC63D3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3CF5F5FD5F61400E9CCD051C3BE26FF9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C14381A0A4314481B22FB2ECA7C705F8 }}

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Deploy WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "dev-ducky-as"
          slot-name: "Production"
          package: ./build
