name: 'Pipeline-React-Main'
on:
  push:
    branches:
      - Develop
  workflow_dispatch:
permissions:
  contents: read
  # id-token: write  # auskommentiert, damit gar kein OIDC-Flow mehr startet
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: Install and build
        run: |
          npm ci --only=production --no-audit --no-fund
          npm run build --if-present
      
      - name: Clean up for deployment
        run: |
          # Remove unnecessary files to reduce package size
          find node_modules -name "*.md" -delete 2>/dev/null || true
          find node_modules -name "*.txt" -delete 2>/dev/null || true
          find node_modules -name "CHANGELOG*" -delete 2>/dev/null || true
          find node_modules -name "README*" -delete 2>/dev/null || true
          find node_modules -name "*.d.ts" -delete 2>/dev/null || true
          find node_modules -name "test" -type d -exec rm -rf {} + 2>/dev/null || true
          find node_modules -name "tests" -type d -exec rm -rf {} + 2>/dev/null || true
          find node_modules -name "__tests__" -type d -exec rm -rf {} + 2>/dev/null || true
          find node_modules -name "*.test.js" -delete 2>/dev/null || true
          find node_modules -name "*.spec.js" -delete 2>/dev/null || true
          # Remove git and other unnecessary files
          rm -rf .git .github *.md
      
      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          auth-type: 'service_principal'
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Wait before deployment
        run: sleep 30
      
      - name: Deploy WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "dev-ducky-as"
          slot-name: "Production"
          package: .
        timeout-minutes: 15
