name: Build and deploy Node.js app to Azure Web App - dev-ducky-as
 
on:
  push:
    branches:
      - Develop
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
 
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
 
      - name: List all files after build (debug)
        run: find . -type f
 
      - name: Detect and zip build folder for deployment
        run: |
          ARTIFACT_FOLDER=$(find . -maxdepth 1 -type d \( -name 'build' -o -name 'dist' -o -name 'out' -o -name '.next' \) | head -n 1 | sed 's|./||')
          if [ -z "$ARTIFACT_FOLDER" ]; then
            echo "❌ No build output folder found (build, dist, out, .next)"
            exit 1
          fi
          echo "Using build output folder: $ARTIFACT_FOLDER"
          zip -r release.zip "$ARTIFACT_FOLDER"
 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
 
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dev-ducky-as'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_75BA8F04F8EA4BD3869E7C92764B2217 }}
