name: 'Pipeline-NextJS-Main'
on:
  push:
    branches:
      - Develop
  workflow_dispatch:
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
            
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build and Export Next.js App
        run: |
          npm run build
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build React App
        run: npm run build
      
      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          auth-type: 'service_principal'
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: Deploy WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "dev-ducky-as"
          slot-name: "Production"
          package: ./build  # Oder ./dist je nach React-Setup
        timeout-minutes: 15/out  # Next.js export erstellt ./out Verzeichnis
        timeout-minutes: 15