name: Build and deploy Node.js app to Azure Web App - dev-ducky-as

on:
  push:
    branches:
      - Develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
  
      - name: npm ci, build and lint
        run: |
          npm ci
          npm run build
          npm run lint --if-present
  
      - name: Upload project for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !.git
            node_modules/
            .next/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dev-ducky-as'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_75BA8F04F8EA4BD3869E7C92764B2217 }}
