name: Build and deploy Node.js app to Azure Web App - dev-ducky-as

on:
  push:
    branches:
      - Develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: List directory to verify build output
        run: ls -alh

      - name: Create deployment package
        run: |
          # Remove development dependencies and clean cache
          npm prune --production
          npm cache clean --force
          
          # Create deployment package with all necessary files
          zip -r release.zip . \
            -x "*.git*" \
            -x "node_modules/.cache/*" \
            -x "*.md" \
            -x ".env*" \
            -x "tests/*" \
            -x "__tests__/*" \
            -x "*.test.js" \
            -x "*.spec.js"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dev-ducky-as'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_75BA8F04F8EA4BD3869E7C92764B2217 }}
