name: 'Pipeline-React-Main'
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  # id-token: write  # auskommentiert, damit gar kein OIDC-Flow mehr startet

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          auth-type: 'service_principal'
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "wa-demoapp-prod-bff3fb24"
          slot-name: "Production"
          package: .
