name: 'Pipeline-React-Main'
on:
  push:
    branches:
      - Develop
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Kann man lassen, falls du irgendwann OIDC brauchst

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          auth-type: 'service_principal'
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "wa-demoapp-prod-bff3fb24"
          slot-name: "Production"
          package: .
